#!/usr/bin/env python3
# Copyright (C) 2026 The FlorisBoard Contributors
# SPDX-License-Identifier: Apache-2.0

"""Generates the Arabic emoji keyword asset (`assets/ime/media/emoji/ar.txt`) by transforming the
English `en.txt` (which carries the canonical grouping/ordering FlorisBoard expects) and swapping
each emoji's name + keywords for the Arabic ones from the CLDR annotation files.

Usage:
  python3 utils/generate_arabic_emoji.py \
      dictionaries/sources/raw/cldr_ar.xml dictionaries/sources/raw/cldr_ar_derived.xml

Emoji without an Arabic annotation keep their English fields, so lookups never regress. The file
format per line is `emoji;name;keyword|keyword|...`, identical to the other locale files.
"""

import re
import sys
import xml.etree.ElementTree as ET

EN_PATH = "app/src/main/assets/ime/media/emoji/en.txt"
OUT_PATH = "app/src/main/assets/ime/media/emoji/ar.txt"
# CLDR uses U+FE0F-less forms for many cp attributes; FlorisBoard lines may carry VS16.
VS16 = "️"


def load_annotations(paths):
    names, keywords = {}, {}
    for path in paths:
        root = ET.parse(path).getroot()
        for node in root.iter("annotation"):
            cp = node.get("cp")
            text = (node.text or "").strip()
            if not cp or not text:
                continue
            if node.get("type") == "tts":
                names.setdefault(cp, text)
            else:
                keywords.setdefault(cp, [k.strip() for k in text.split("|") if k.strip()])
    return names, keywords


def lookup(table, emoji):
    if emoji in table:
        return table[emoji]
    stripped = emoji.replace(VS16, "")
    if stripped in table:
        return table[stripped]
    return None


def main():
    ann_paths = sys.argv[1:] or [
        "dictionaries/sources/raw/cldr_ar.xml",
        "dictionaries/sources/raw/cldr_ar_derived.xml",
    ]
    names, keywords = load_annotations(ann_paths)

    translated = kept = 0
    out_lines = [
        "# Auto-generated by generate_arabic_emoji.py from en.txt + CLDR Arabic annotations",
        "# DO NOT EDIT MANUALLY!",
    ]
    with open(EN_PATH, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if not line or line.startswith("#") or line.startswith("["):
                if not line.startswith("#"):
                    out_lines.append(line)
                continue
            parts = line.split(";")
            if len(parts) < 2:
                out_lines.append(line)
                continue
            emoji = parts[0]
            ar_name = lookup(names, emoji)
            ar_keywords = lookup(keywords, emoji)
            if ar_name or ar_keywords:
                translated += 1
                name = ar_name or parts[1]
                kws = "|".join(ar_keywords) if ar_keywords else (parts[2] if len(parts) > 2 else "")
                out_lines.append(f"{emoji};{name};{kws}" if kws else f"{emoji};{name}")
            else:
                kept += 1
                out_lines.append(line)

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines) + "\n")
    print(f"wrote {OUT_PATH}: {translated} emoji with Arabic fields, {kept} kept English")


if __name__ == "__main__":
    main()
